### PR TITLE
Import the `substream` function from the same context

### PR DESCRIPTION
**Pull request by lpinca**
See #10.

### CODE REVIEW

**Comment by lpinca** [comment]
@3rd-Eden LGTY?

**Comment by 3rd-Eden** [comment]
LGTM, but merge conflict :p

**Comment by lpinca** [comment]
Gonna fix it.

**Comment by lpinca** [comment]
Is it ok if I publish this as `0.2.0`?

**Comment by 3rd-Eden** [comment]
Yup!

**Pull request merged**
